name: Sync Data to OSS

on:
  push:
    branches: [ main ]
    paths:
      - 'data/input/**'
  workflow_dispatch:  # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          
      - name: Install dependencies
        run: npm install xlsx ali-oss
        
      - name: Convert data
        run: node scripts/convert-data.js
        
      - name: Upload to Aliyun OSS
        run: node scripts/upload-to-oss.js
        env:
          OSS_REGION: ${{ secrets.OSS_REGION }}
          OSS_ACCESS_KEY_ID: ${{ secrets.OSS_ACCESS_KEY_ID }}
          OSS_ACCESS_KEY_SECRET: ${{ secrets.OSS_ACCESS_KEY_SECRET }}
          OSS_BUCKET: ${{ secrets.OSS_BUCKET }}
